spring:
  profile:
  said: 
    name1: "name1"
    name2: "name2"
---

spring:
  profile : dev
  said : DEV SERVER

---

spring:
  profile : real
  said : REAL SERVER

---

spring:
  profile : beta
  said : BETA SERVE
